<?php
namespace app\home\controller;

use app\BaseController;
use think\exception\HttpResponseException;

class Base extends BaseController{
    public $adminUser = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (empty($this->is_login())){
            return $this->redirect('/web/login');
        }
    }

    public function is_login(){
        $this->adminUser = session(config('admin.session_admin'));
        if (empty($this->adminUser)){
            return false;
        }
        return true;
    }

    public function redirect(...$args){
        throw new HttpResponseException(redirect(...$args));
    }
}